# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-31 06:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0004_auto_20181006_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('tracking_id', models.CharField(blank=True, max_length=100)),
                ('qty', models.IntegerField(default=False)),
                ('order_status', models.CharField(choices=[('P', 'Pre-Booked'), ('B', 'Booked'), ('D', 'Dispatched'), ('R', 'Delivered'), ('C', 'Cancelled')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ClientType')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('dealer_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Dealer')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Reseller')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ItemType')),
            ],
        ),
    ]
