# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-01 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181101_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_code', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
