# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-02 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20181102_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='profit',
        ),
    ]
