# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181106_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
