# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-06 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group/'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
