# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20181006_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group/'),
        ),
    ]
