# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20180929_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(default='s11111', max_length=150),
            preserve_default=False,
        ),
    ]
