# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_itemtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
