# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20180929_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(default='s22222222', max_length=100),
            preserve_default=False,
        ),
    ]
