# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_itemgroup_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemgroup',
            old_name='all_time_available',
            new_name='available',
        ),
    ]
