# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20180929_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemgroup',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
