# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_auto_20180929_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstock',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
