# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-29 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_auto_20180929_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'ordering': ('group',)},
        ),
        migrations.AlterModelOptions(
            name='itemstock',
            options={'ordering': ('item_name',)},
        ),
        migrations.AlterIndexTogether(
            name='itemgroup',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='itemstock',
            index_together=set([('id', 'slug')]),
        ),
    ]
