# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181022_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=0),
        ),
    ]
