# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
